services:
  postgres:
    image: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: anybody_here_chat_db
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    ports:
      - "8180:80"
    environment:
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com

  chat-app:
    build: .
    image: chat-app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - "JDBC_URL=jdbc:postgresql://postgres:5432/anybody_here_chat_db"
      - "DB_USER=postgres"
      - "DB_PASS=postgres"