openapi: 3.0.3
info:
  title: Anybody Here Chat
  description: >
    A robust and scalable real-time chat application
  license:
    name: MIT
    url: https://github.com/paulofranklim/anybody-here-chat/blob/main/LICENSE
  version: 0.0.1
servers:
  - url: http://anybodyhere.chat
tags:
  - name: contact
    description: contact domain implementation

paths:
  /contact:
    post:
      tags:
        - contact
      summary: Add a new contact to user contacts list
      description: Add a new contact to user contacts list
      operationId: addContact
      requestBody:
        description: Add a new contact to user contacts list
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactRequestDTO'
        required: true
      responses:
        '200':
          description: Contact added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '400':
          description: Invalid input

  /contact/{userId}:
    get:
      tags:
        - contact
      summary: Finds all contacts by user
      description: Return a list of all user's contacts
      operationId: getUserContacts
      parameters:
        - name: userId
          in: path
          description: ID of user that needs to be fetched
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        '400':
          description: Invalid user id

components:
  schemas:
    GenericResponse:
      description: The generic api response
      type: object
      properties:
        summary:
          type: string
        data:
          type: object

    ContactRequestDTO:
      description: The new contact to add request
      type: object
      properties:
        userId:
          description: User id
          type: integer
          format: int64
        contactId:
          description: Contact id
          type: integer
          format: int64
